spring:
  config:
    activate:
      on-profile: local

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/trading?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always

  cache:
    type: redis

  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers:
      - 'localhost:9092'