spring:
  config:
    activate:
      on-profile: local

  jpa:
    database: h2

    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:trading;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: never

