spring:
  config:
    activate:
      on-profile: local

  jpa:
    database: Mysql

    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/trading
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: always

  data:
    redis:
      host: localhost
      port: 6379