
    create table inventory (
        created_at timestamp(6),
        id bigint generated by default as identity,
        item_id bigint,
        member_id bigint,
        modified_at timestamp(6),
        primary key (id)
    );

    create table item (
        price integer not null,
        type tinyint check (type between 0 and 4),
        created_at timestamp(6),
        id bigint generated by default as identity,
        modified_at timestamp(6),
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table item_sale_info (
        created_at timestamp(6),
        id bigint generated by default as identity,
        modified_at timestamp(6),
        primary key (id)
    );

    create table item_search_keyword (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table member (
        created_at timestamp(6),
        id bigint generated by default as identity,
        modified_at timestamp(6),
        point bigint,
        name varchar(255),
        phone varchar(255),
        primary key (id)
    );

    create table point_transaction (
        id bigint generated by default as identity,
        member_id bigint,
        point bigint,
        transacted_at timestamp(6),
        transaction_type enum ('CHARGE','USE'),
        primary key (id)
    );

    create table stock (
        id bigint generated by default as identity,
        primary key (id)
    );
